name: image_compressor
description: Simple image resizer for jpg, jpeg and png files
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.17
  file_selector: ^1.0.3
  get:
  window_manager: ^0.3.6
  getwidget: ^4.0.0
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo.png
  fonts:
    - family: Orbitron
      fonts:
        - asset: lib/assets/fonts/Orbitron/Orbitron-Regular.ttf
        - asset: lib/assets/fonts/Orbitron/Orbitron-Medium.ttf
        - asset: lib/assets/fonts/Orbitron/Orbitron-Bold.ttf
